In [1]:
import numpy as np
import pandas as pd
 
df = pd.read_csv('C:/Users/Orestis/Desktop/1.Diplomatiki/Data/Item Data/imagenewsreel-itemData.csv', delimiter=';', header=None, escapechar='\\', quotechar='\"')
df.columns = ['id','imageId','title','publisher','url','image_url','stemmed','date','article_id']
df.shape

(51397, 9)

In [2]:
#sbinw tis NaN
nonull_df = df.dropna(how='any', axis = 0)
nonull_df.shape

(51368, 9)

In [3]:
final_df = nonull_df.drop_duplicates(subset = 'article_id')
final_df.shape,type(final_df)

((51260, 9), pandas.core.frame.DataFrame)

In [4]:
#dimiourgia dictionary me tous 5 publishers
pub_dict = {}   
counter = 0
for publisher in final_df['publisher']:
        if publisher not in pub_dict:
            pub_dict[publisher] = counter
            counter+=1
pub_dict

{17614: 0, 1677: 1, 39234: 2, 13554: 3, 694: 4}

In [7]:
#antistoixisi publisher value se kathe arthro
publishers = []
for x in final_df['publisher']:
    publishers.append(pub_dict[x])
len(publishers)   # den exw bgalei ta null entries

51260

In [13]:
#prosthetw tin stili me tous publishers sto dataframe
final_df['pub_code'] = publishers

C:\Users\Orestis\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [17]:
final_df.shape,final_df['pub_code'].head()

((51260, 10), 0    0
 1    1
 2    1
 3    1
 4    1
 Name: pub_code, dtype: int64)

In [18]:
import pickle

with open("publisher_codes.pk", 'wb') as handle:
    pickle.dump(publishers, handle, protocol=pickle.HIGHEST_PROTOCOL)


In [9]:
#Dimiourgia one hot vector...gia kathe arthro(rows) tha einai oloi oi publisher (rows) mhden ektos apo auton opou dimosieutike(=1)
#arxikopoiw ton vector mouy me mhdenika
N = np.zeros([len(df),5])
N

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
#enumerate(my_list) epistrefei ena tuple (index tis thesis-row opou brisketai sthn lista, periexomeno tis listas stin thesi auth)
for article,publ in enumerate(df[10]):
    N[article][publ] = 1    
N    

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [ ]:
import pickle

with open("publishers.pk", 'wb') as handle:
    pickle.dump(words_list, handle, protocol=pickle.HIGHEST_PROTOCOL)


In [20]:
test = np.zeros([4,4])
test[0][3]= 5
test

array([[0., 0., 0., 5.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
type(publishers)

list